name: Workflow Evento
run-name: Exemplo de Pull Request
on:
  pull_request:
    branches: ["master", "feat/*", "release/*"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Action apenas executada em master e features"