name: Workflow Schedule
on:
  workflow_dispatch:
jobs:
  teste:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Action apenas executada em master e features"