name: Workflow Evento
on:
  push:
    branches: ["master", "feat/*"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Action apenas executada em master e features"