name: Workflow Concurrency
run-name: Workflow Concurrency ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      chave:
        type: string
        description: "Concurrency key"
concurrency: ${{ inputs.chave }}
jobs:
  execution-flow:
    runs-on: ubuntu-latest
    steps:
    - name: Execution of Test Job
      run: |
        sleep 120;
        echo "Action executed on job 01"