name: Functions
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "Username"
        default: "Nino"
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Validate Name
        run: echo "${{ github.actor == inputs.name}}"